// AUTO-GENERATED BY tools/gen_platform.sh
// Do not edit manually.

import React from "react";
import { Routes, Route, Navigate } from "react-router-dom";
import { useAuth, getLandingPathForRole } from "../context/AuthContext.jsx";

import AdminAdminDashboard from "../pages/admin/AdminDashboard.jsx";
import AdminAdminLedger from "../pages/admin/AdminLedger.jsx";
import AdminAdminRisk from "../pages/admin/AdminRisk.jsx";
import AdminAdminSystem from "../pages/admin/AdminSystem.jsx";
import AdminAdminUsers from "../pages/admin/AdminUsers.jsx";
import AdminAlphaDecay from "../pages/admin/AlphaDecay.jsx";
import AdminAlphaDecaySurface from "../pages/admin/AlphaDecaySurface.jsx";
import AdminAlphaMap from "../pages/admin/AlphaMap.jsx";
import AdminAlphaNotebook from "../pages/admin/AlphaNotebook.jsx";
import AdminArbitrageRadar from "../pages/admin/ArbitrageRadar.jsx";
import AdminBaselMetrics from "../pages/admin/BaselMetrics.jsx";
import AdminBroadcast from "../pages/admin/Broadcast.jsx";
import AdminCapacity from "../pages/admin/Capacity.jsx";
import AdminCapacityEstimator from "../pages/admin/CapacityEstimator.jsx";
import AdminCapitalFlows from "../pages/admin/CapitalFlows.jsx";
import AdminCarryEngine from "../pages/admin/CarryEngine.jsx";
import AdminCompliance from "../pages/admin/Compliance.jsx";
import AdminCorrelation from "../pages/admin/Correlation.jsx";
import AdminCorrelationRegime from "../pages/admin/CorrelationRegime.jsx";
import AdminCostForecaster from "../pages/admin/CostForecaster.jsx";
import AdminCrossAsset from "../pages/admin/CrossAsset.jsx";
import AdminDisasterRecovery from "../pages/admin/DisasterRecovery.jsx";
import AdminExecutionAttribution from "../pages/admin/ExecutionAttribution.jsx";
import AdminExecutionFootprint from "../pages/admin/ExecutionFootprint.jsx";
import AdminExecutionQuality from "../pages/admin/ExecutionQuality.jsx";
import AdminExecutionReplay from "../pages/admin/ExecutionReplay.jsx";
import AdminExecutionRisk from "../pages/admin/ExecutionRisk.jsx";
import AdminExecutionScenarioLab from "../pages/admin/ExecutionScenarioLab.jsx";
import AdminExecutionSuperConsole from "../pages/admin/ExecutionSuperConsole.jsx";
import AdminFeatureFlags from "../pages/admin/FeatureFlags.jsx";
import AdminForecastEngine from "../pages/admin/ForecastEngine.jsx";
import AdminFunding from "../pages/admin/Funding.jsx";
import AdminGlobalCommandCenter from "../pages/admin/GlobalCommandCenter.jsx";
import AdminGlobalMacro from "../pages/admin/GlobalMacro.jsx";
import AdminImpersonation from "../pages/admin/Impersonation.jsx";
import AdminInternalTools from "../pages/admin/InternalTools.jsx";
import AdminLatencyArb from "../pages/admin/LatencyArb.jsx";
import AdminLatencyProfiler from "../pages/admin/LatencyProfiler.jsx";
import AdminLeadLag from "../pages/admin/LeadLag.jsx";
import AdminLiquidity from "../pages/admin/Liquidity.jsx";
import AdminLiquidityEngine from "../pages/admin/LiquidityEngine.jsx";
import AdminLiquidityFracture from "../pages/admin/LiquidityFracture.jsx";
import AdminLiquidityFragmentation from "../pages/admin/LiquidityFragmentation.jsx";
import AdminLiquidityMap from "../pages/admin/LiquidityMap.jsx";
import AdminLiquidityShockboard from "../pages/admin/LiquidityShockboard.jsx";
import AdminLiquidityStress from "../pages/admin/LiquidityStress.jsx";
import AdminLiqVolObservatory from "../pages/admin/LiqVolObservatory.jsx";
import AdminMacroEarlyWarning from "../pages/admin/MacroEarlyWarning.jsx";
import AdminMacroMicroFusionBoard from "../pages/admin/MacroMicroFusionBoard.jsx";
import AdminMacroRegime from "../pages/admin/MacroRegime.jsx";
import AdminMacroStress from "../pages/admin/MacroStress.jsx";
import AdminMarketFusion from "../pages/admin/MarketFusion.jsx";
import AdminMarketIntelligence from "../pages/admin/MarketIntelligence.jsx";
import AdminMarketMaking from "../pages/admin/MarketMaking.jsx";
import AdminMarketReplay from "../pages/admin/MarketReplay.jsx";
import AdminMarketStability from "../pages/admin/MarketStability.jsx";
import AdminMarketStateMachine from "../pages/admin/MarketStateMachine.jsx";
import AdminMatchingEngine from "../pages/admin/MatchingEngine.jsx";
import AdminMetaAnalyzer from "../pages/admin/MetaAnalyzer.jsx";
import AdminMicroCrash from "../pages/admin/MicroCrash.jsx";
import AdminMicroRegime from "../pages/admin/MicroRegime.jsx";
import AdminMicrostructure from "../pages/admin/Microstructure.jsx";
import AdminMicrostructureReplay from "../pages/admin/MicrostructureReplay.jsx";
import AdminMultiStrategy from "../pages/admin/MultiStrategy.jsx";
import AdminMultiTenant from "../pages/admin/MultiTenant.jsx";
import AdminObservability from "../pages/admin/Observability.jsx";
import AdminOptionsMM from "../pages/admin/OptionsMM.jsx";
import AdminOrderFlowLab from "../pages/admin/OrderFlowLab.jsx";
import AdminPortfolioOptimizer from "../pages/admin/PortfolioOptimizer.jsx";
import AdminPortfolioRisk from "../pages/admin/PortfolioRisk.jsx";
import AdminRegimeAtlas from "../pages/admin/RegimeAtlas.jsx";
import AdminRegimePortfolio from "../pages/admin/RegimePortfolio.jsx";
import AdminRegulatory from "../pages/admin/Regulatory.jsx";
import AdminRiskCenter from "../pages/admin/RiskCenter.jsx";
import AdminRiskFirewall from "../pages/admin/RiskFirewall.jsx";
import AdminRiskParity from "../pages/admin/RiskParity.jsx";
import AdminRobustnessLab from "../pages/admin/RobustnessLab.jsx";
import AdminShockPropagation from "../pages/admin/ShockPropagation.jsx";
import AdminSignalOrtho from "../pages/admin/SignalOrtho.jsx";
import AdminSmartHedger from "../pages/admin/SmartHedger.jsx";
import AdminSmartRouter from "../pages/admin/SmartRouter.jsx";
import AdminStrategyDrift from "../pages/admin/StrategyDrift.jsx";
import AdminStrategyLifecycle from "../pages/admin/StrategyLifecycle.jsx";
import AdminStrategyStressLab from "../pages/admin/StrategyStressLab.jsx";
import AdminStrategySuperLab from "../pages/admin/StrategySuperLab.jsx";
import AdminStressCorrelation from "../pages/admin/StressCorrelation.jsx";
import AdminStressGenerator from "../pages/admin/StressGenerator.jsx";
import AdminSyntheticLab from "../pages/admin/SyntheticLab.jsx";
import AdminSystemicRisk from "../pages/admin/SystemicRisk.jsx";
import AdminTailRisk from "../pages/admin/TailRisk.jsx";
import AdminTermStructure from "../pages/admin/TermStructure.jsx";
import AdminTimingAlpha from "../pages/admin/TimingAlpha.jsx";
import AdminTrendEngine from "../pages/admin/TrendEngine.jsx";
import AdminVolCarry from "../pages/admin/VolCarry.jsx";
import AdminVolInteraction from "../pages/admin/VolInteraction.jsx";
import AdminVolRegime from "../pages/admin/VolRegime.jsx";
import AdminVolSurface from "../pages/admin/VolSurface.jsx";
import AdminVolSurfaceRegime from "../pages/admin/VolSurfaceRegime.jsx";
import AdminYieldCurve from "../pages/admin/YieldCurve.jsx";
import AppAdmin from "../pages/app/Admin.jsx";
import AppApiDocs from "../pages/app/ApiDocs.jsx";
import AppApiKeys from "../pages/app/ApiKeys.jsx";
import AppAuditLogs from "../pages/app/AuditLogs.jsx";
import AppBilling from "../pages/app/Billing.jsx";
import AppBranding from "../pages/app/Branding.jsx";
import AppDashboard from "../pages/app/Dashboard.jsx";
import AppDataExport from "../pages/app/DataExport.jsx";
import AppDeveloperPlayground from "../pages/app/DeveloperPlayground.jsx";
import AppLedger from "../pages/app/Ledger.jsx";
import AppMarket from "../pages/app/Market.jsx";
import AppNotifications from "../pages/app/Notifications.jsx";
import AppNotificationTemplates from "../pages/app/NotificationTemplates.jsx";
import AppOrderEntry from "../pages/app/OrderEntry.jsx";
import AppPortfolio from "../pages/app/Portfolio.jsx";
import AppPositions from "../pages/app/Positions.jsx";
import AppSettings from "../pages/app/Settings.jsx";
import AppSupport from "../pages/app/Support.jsx";
import AppSystemStatus from "../pages/app/SystemStatus.jsx";
import AppTrading from "../pages/app/Trading.jsx";
import AppUserActivity from "../pages/app/UserActivity.jsx";
import AppUserProfile2 from "../pages/app/UserProfile2.jsx";
import AppWebhooks from "../pages/app/Webhooks.jsx";
import PublicLanding from "../pages/public/Landing.jsx";
import PublicLegalPrivacy from "../pages/public/LegalPrivacy.jsx";
import PublicLegalRisk from "../pages/public/LegalRisk.jsx";
import PublicLegalTerms from "../pages/public/LegalTerms.jsx";
import PublicLogin from "../pages/public/Login.jsx";
import PublicPrivacy from "../pages/public/Privacy.jsx";
import PublicRiskDisclosure from "../pages/public/RiskDisclosure.jsx";
import PublicSupport from "../pages/public/Support.jsx";
import PublicTerms from "../pages/public/Terms.jsx";

function RoleLandingRedirect() {
  const { user } = useAuth();
  const target = getLandingPathForRole(user.role);
  return <Navigate to={target} replace />;
}

export default function GeneratedRoutes() {
  return (
    <Routes>
      {/* Root: role-based landing */}
      <Route path="/" element={<RoleLandingRedirect />} />
      <Route path="/pub/lnd" element={<PublicLanding />} />
      <Route path="/adm/dash" element={<AdminAdminDashboard />} />
      <Route path="/adm/led" element={<AdminAdminLedger />} />
      <Route path="/adm/rsk" element={<AdminAdminRisk />} />
      <Route path="/adm/sys" element={<AdminAdminSystem />} />
      <Route path="/adm/usr" element={<AdminAdminUsers />} />
      <Route path="/adm/dec" element={<AdminAlphaDecay />} />
      <Route path="/adm/alp" element={<AdminAlphaDecaySurface />} />
      <Route path="/adm/alp" element={<AdminAlphaMap />} />
      <Route path="/adm/alp" element={<AdminAlphaNotebook />} />
      <Route path="/adm/arb" element={<AdminArbitrageRadar />} />
      <Route path="/adm/bas" element={<AdminBaselMetrics />} />
      <Route path="/adm/bro" element={<AdminBroadcast />} />
      <Route path="/adm/cap" element={<AdminCapacity />} />
      <Route path="/adm/cap" element={<AdminCapacityEstimator />} />
      <Route path="/adm/cap" element={<AdminCapitalFlows />} />
      <Route path="/adm/car" element={<AdminCarryEngine />} />
      <Route path="/adm/com" element={<AdminCompliance />} />
      <Route path="/adm/cor" element={<AdminCorrelation />} />
      <Route path="/adm/cor" element={<AdminCorrelationRegime />} />
      <Route path="/adm/cos" element={<AdminCostForecaster />} />
      <Route path="/adm/cro" element={<AdminCrossAsset />} />
      <Route path="/adm/dis" element={<AdminDisasterRecovery />} />
      <Route path="/adm/exe" element={<AdminExecutionAttribution />} />
      <Route path="/adm/exe" element={<AdminExecutionFootprint />} />
      <Route path="/adm/exe" element={<AdminExecutionQuality />} />
      <Route path="/adm/rep" element={<AdminExecutionReplay />} />
      <Route path="/adm/exe" element={<AdminExecutionRisk />} />
      <Route path="/adm/exe" element={<AdminExecutionScenarioLab />} />
      <Route path="/adm/exe" element={<AdminExecutionSuperConsole />} />
      <Route path="/adm/fea" element={<AdminFeatureFlags />} />
      <Route path="/adm/for" element={<AdminForecastEngine />} />
      <Route path="/adm/fun" element={<AdminFunding />} />
      <Route path="/adm/glo" element={<AdminGlobalCommandCenter />} />
      <Route path="/adm/glo" element={<AdminGlobalMacro />} />
      <Route path="/adm/imp" element={<AdminImpersonation />} />
      <Route path="/adm/int" element={<AdminInternalTools />} />
      <Route path="/adm/lat" element={<AdminLatencyArb />} />
      <Route path="/adm/lat" element={<AdminLatencyProfiler />} />
      <Route path="/adm/lea" element={<AdminLeadLag />} />
      <Route path="/adm/liq" element={<AdminLiquidity />} />
      <Route path="/adm/liq" element={<AdminLiquidityEngine />} />
      <Route path="/adm/liq" element={<AdminLiquidityFracture />} />
      <Route path="/adm/liq" element={<AdminLiquidityFragmentation />} />
      <Route path="/adm/map" element={<AdminLiquidityMap />} />
      <Route path="/adm/liq" element={<AdminLiquidityShockboard />} />
      <Route path="/adm/liq" element={<AdminLiquidityStress />} />
      <Route path="/adm/liq" element={<AdminLiqVolObservatory />} />
      <Route path="/adm/mac" element={<AdminMacroEarlyWarning />} />
      <Route path="/adm/mac" element={<AdminMacroMicroFusionBoard />} />
      <Route path="/adm/mac" element={<AdminMacroRegime />} />
      <Route path="/adm/mac" element={<AdminMacroStress />} />
      <Route path="/adm/mar" element={<AdminMarketFusion />} />
      <Route path="/adm/mar" element={<AdminMarketIntelligence />} />
      <Route path="/adm/mar" element={<AdminMarketMaking />} />
      <Route path="/adm/mar" element={<AdminMarketReplay />} />
      <Route path="/adm/mar" element={<AdminMarketStability />} />
      <Route path="/adm/mar" element={<AdminMarketStateMachine />} />
      <Route path="/adm/mat" element={<AdminMatchingEngine />} />
      <Route path="/adm/met" element={<AdminMetaAnalyzer />} />
      <Route path="/adm/mic" element={<AdminMicroCrash />} />
      <Route path="/adm/mic" element={<AdminMicroRegime />} />
      <Route path="/adm/mic" element={<AdminMicrostructure />} />
      <Route path="/adm/mic" element={<AdminMicrostructureReplay />} />
      <Route path="/adm/mul" element={<AdminMultiStrategy />} />
      <Route path="/adm/mul" element={<AdminMultiTenant />} />
      <Route path="/adm/obs" element={<AdminObservability />} />
      <Route path="/adm/opt" element={<AdminOptionsMM />} />
      <Route path="/adm/ord" element={<AdminOrderFlowLab />} />
      <Route path="/adm/por" element={<AdminPortfolioOptimizer />} />
      <Route path="/adm/rsk" element={<AdminPortfolioRisk />} />
      <Route path="/adm/reg" element={<AdminRegimeAtlas />} />
      <Route path="/adm/reg" element={<AdminRegimePortfolio />} />
      <Route path="/adm/reg" element={<AdminRegulatory />} />
      <Route path="/adm/rsk" element={<AdminRiskCenter />} />
      <Route path="/adm/ris" element={<AdminRiskFirewall />} />
      <Route path="/adm/ris" element={<AdminRiskParity />} />
      <Route path="/adm/rob" element={<AdminRobustnessLab />} />
      <Route path="/adm/sho" element={<AdminShockPropagation />} />
      <Route path="/adm/sig" element={<AdminSignalOrtho />} />
      <Route path="/adm/sma" element={<AdminSmartHedger />} />
      <Route path="/adm/sma" element={<AdminSmartRouter />} />
      <Route path="/adm/str" element={<AdminStrategyDrift />} />
      <Route path="/adm/str" element={<AdminStrategyLifecycle />} />
      <Route path="/adm/str" element={<AdminStrategyStressLab />} />
      <Route path="/adm/str" element={<AdminStrategySuperLab />} />
      <Route path="/adm/str" element={<AdminStressCorrelation />} />
      <Route path="/adm/str" element={<AdminStressGenerator />} />
      <Route path="/adm/syn" element={<AdminSyntheticLab />} />
      <Route path="/adm/sys" element={<AdminSystemicRisk />} />
      <Route path="/adm/tai" element={<AdminTailRisk />} />
      <Route path="/adm/ter" element={<AdminTermStructure />} />
      <Route path="/adm/tim" element={<AdminTimingAlpha />} />
      <Route path="/adm/tre" element={<AdminTrendEngine />} />
      <Route path="/adm/vol" element={<AdminVolCarry />} />
      <Route path="/adm/vol" element={<AdminVolInteraction />} />
      <Route path="/adm/vol" element={<AdminVolRegime />} />
      <Route path="/adm/vol" element={<AdminVolSurface />} />
      <Route path="/adm/vol" element={<AdminVolSurfaceRegime />} />
      <Route path="/adm/yie" element={<AdminYieldCurve />} />
      <Route path="/app/adm" element={<AppAdmin />} />
      <Route path="/app/api" element={<AppApiDocs />} />
      <Route path="/app/api" element={<AppApiKeys />} />
      <Route path="/app/aud" element={<AppAuditLogs />} />
      <Route path="/app/bil" element={<AppBilling />} />
      <Route path="/app/bra" element={<AppBranding />} />
      <Route path="/app/dash" element={<AppDashboard />} />
      <Route path="/app/dat" element={<AppDataExport />} />
      <Route path="/app/dev" element={<AppDeveloperPlayground />} />
      <Route path="/app/led" element={<AppLedger />} />
      <Route path="/app/mkt" element={<AppMarket />} />
      <Route path="/app/not" element={<AppNotifications />} />
      <Route path="/app/ntp" element={<AppNotificationTemplates />} />
      <Route path="/app/ord" element={<AppOrderEntry />} />
      <Route path="/app/pfl" element={<AppPortfolio />} />
      <Route path="/app/pos" element={<AppPositions />} />
      <Route path="/app/set" element={<AppSettings />} />
      <Route path="/app/sup" element={<AppSupport />} />
      <Route path="/app/sts" element={<AppSystemStatus />} />
      <Route path="/app/trd" element={<AppTrading />} />
      <Route path="/app/use" element={<AppUserActivity />} />
      <Route path="/app/use" element={<AppUserProfile2 />} />
      <Route path="/app/web" element={<AppWebhooks />} />
      <Route path="/pub/lnd" element={<PublicLanding />} />
      <Route path="/pub/lpr" element={<PublicLegalPrivacy />} />
      <Route path="/pub/lrk" element={<PublicLegalRisk />} />
      <Route path="/pub/ter" element={<PublicLegalTerms />} />
      <Route path="/pub/lgn" element={<PublicLogin />} />
      <Route path="/pub/pri" element={<PublicPrivacy />} />
      <Route path="/pub/ris" element={<PublicRiskDisclosure />} />
      <Route path="/pub/sup" element={<PublicSupport />} />
      <Route path="/pub/ter" element={<PublicTerms />} />
      <Route path="*" element={<div>Not Found</div>} />
    </Routes>
  );
}
