apiVersion: batch/v1
kind: Job
metadata:
  name: identity-schema-init
  namespace: trading-platform
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: cockroachdb/cockroach:v24.1.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Running Identity Domain migrations..."

              cockroach sql --insecure \
                --host=cockroachdb-0.cockroachdb.trading-platform.svc.cluster.local:26257 \
                --file=/migrations/identity.sql

              echo "Identity migrations completed."
          volumeMounts:
            - name: migration-sql
              mountPath: /migrations
      volumes:
        - name: migration-sql
          configMap:
            name: identity-schema
            items:
              - key: identity.sql
                path: identity.sql

