config:
  cluster:
    enabled: true
    replicas: 3
    noAdvertise: false

  jetstream:
    enabled: true
    fileStore:
      enabled: true
      pvc:
        enabled: true
        size: 10Gi

natsBox:
  enabled: true

