apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: infra
spec:
  type: ClusterIP
  selector:
    app: ledger-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http

