apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
  namespace: trading-platform
spec:
  serviceName: cockroachdb
  replicas: 1
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:v23.2.5
          command:
            - "/cockroach/cockroach"
          args:
            - "start-single-node"
            - "--insecure"
            - "--listen-addr=0.0.0.0:26257"
            - "--http-addr=0.0.0.0:8080"
            - "--cache=128Mi"
            - "--max-sql-memory=128Mi"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          ports:
            - containerPort: 26257
              name: sql
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: datadir
              mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

