apiVersion: v1
kind: ConfigMap
metadata:
  name: cockroach-config
  namespace: trading-platform
data:
  DATABASE_HOST: cockroachdb-public.trading-platform.svc.cluster.local
  DATABASE_PORT: "26257"
  DATABASE_NAME: gqx_db

