kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: trading
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            system-reserved: memory=1Gi
            kube-reserved: memory=1Gi
            eviction-hard: memory.available<500Mi
  - role: worker
  - role: worker
  - role: worker

