apiVersion: batch/v1
kind: Job
metadata:
  name: ledger-pytest-debug
  namespace: infra
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: debug
          image: registry.bassteck.com/ledger-pytest:latest
          command: ["sleep"]
          args: ["infinity"]

