apiVersion: batch/v1
kind: Job
metadata:
  name: ledger-pytest
  namespace: infra
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ledger-pytest
          image: ledger-pytest:latest
          imagePullPolicy: IfNotPresent
          workingDir: /app
          env:
            - name: TEST_DATABASE_URL
              value: "postgresql://bassteck:bassteck123@postgres.infra.svc.cluster.local:5432/trading"
            - name: ENV
              value: "pytest"
          command: ["pytest"]
          args:
            - "-vv"
            - "--disable-warnings"
            - "--maxfail=1"
            - "test/"
