apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-public
  namespace: trading-platform
  labels:
    app: cockroachdb
spec:
  type: ClusterIP
  selector:
    app: cockroachdb
  ports:
    - name: grpc
      port: 26257
      targetPort: 26257
    - name: http
      port: 8080
      targetPort: 8080

