apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
  namespace: trading-platform
  labels:
    app: cockroachdb
spec:
  serviceName: cockroachdb
  replicas: 3
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:v23.2.5
          imagePullPolicy: IfNotPresent
          args:
            - start
            - --insecure
            - --advertise-addr=$(HOSTNAME).cockroachdb.trading-platform.svc.cluster.local
            - --join=cockroachdb-0.cockroachdb.trading-platform.svc.cluster.local:26257,cockroachdb-1.cockroachdb.trading-platform.svc.cluster.local:26257,cockroachdb-2.cockroachdb.trading-platform.svc.cluster.local:26257
            - --listen-addr=0.0.0.0:26257
            - --sql-addr=0.0.0.0:26257
            - --http-addr=0.0.0.0:8080
            - --cache=25%
            - --max-sql-memory=25%
            - --store=/cockroach/cockroach-data
          ports:
            - containerPort: 26257
              name: grpc
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: datadir
              mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

