#!/bin/bash

OUT="../src/layout/GeneratedRoutes.jsx"
ROOT="../src/pages"

echo "🚀 Generating clean GeneratedRoutes.jsx → $OUT"

# 1. If the file exists, delete it to avoid duplicates
if [ -f "$OUT" ]; then
  echo "🧹 Removing old GeneratedRoutes.jsx"
  rm "$OUT"
fi

# 2. Start writing a fresh file
cat > "$OUT" << 'EOF'
// AUTO-GENERATED BY tools/gen_routes.sh
// Do not edit manually.

import React from "react";
import { Routes, Route } from "react-router-dom";
EOF

echo "" >> "$OUT"

# 3. Collect all JSX page files (admin, app, public only)
FILES=$(find "$ROOT" -type f -name "*.jsx" \
  | grep -E "pages/(admin|app|public)/" \
  | sort)

# 4. Generate imports with folder‑aware unique component names
COMPONENTS=()

for FILE in $FILES; do
  REL=${FILE#../src/}                     # pages/public/legal/LegalRisk.jsx
  IMPORT_PATH="../${REL%.jsx}"            # ../pages/public/legal/LegalRisk
  CATEGORY=$(echo "$REL" | cut -d'/' -f2) # admin | app | public

  SUBPATH=$(dirname "${REL#pages/$CATEGORY/}")  # legal
  NAME=$(basename "$REL" .jsx)                  # LegalRisk

  if [[ "$SUBPATH" == "." ]]; then
    FOLDER_PART=""
  else
    FOLDER_PART=$(echo "$SUBPATH" | sed -E 's/(^|\/)([a-z])/\U\2/g' | tr -d '/')
  fi

  CAP_CAT="$(tr '[:lower:]' '[:upper:]' <<< ${CATEGORY:0:1})${CATEGORY:1}"
  COMPONENT_NAME="${CAP_CAT}${FOLDER_PART}${NAME}"

  COMPONENTS+=("$CATEGORY|$SUBPATH|$NAME|$COMPONENT_NAME")

  echo "import ${COMPONENT_NAME} from \"${IMPORT_PATH}.jsx\";" >> "$OUT"
done

# 5. Begin component
cat >> "$OUT" << 'EOF'

export default function GeneratedRoutes() {
  return (
    <Routes>
EOF

# 6. Add root route using the generated PublicLanding component
for ITEM in "${COMPONENTS[@]}"; do
  IFS="|" read CATEGORY SUBPATH NAME COMPONENT_NAME <<< "$ITEM"
  if [[ "$CATEGORY" == "public" && "$NAME" == "Landing" ]]; then
    echo "      <Route path=\"/\" element={<${COMPONENT_NAME} />} />" >> "$OUT"
  fi
done

# 7. Generate nested routes
for ITEM in "${COMPONENTS[@]}"; do
  IFS="|" read CATEGORY SUBPATH NAME COMPONENT_NAME <<< "$ITEM"

  KEYPATH=$(echo "$NAME" | sed -E 's/([A-Z])/-\L\1/g' | sed 's/^-//')

  if [[ "$SUBPATH" == "." ]]; then
    ROUTE="/${CATEGORY}/${KEYPATH}"
  else
    ROUTE="/${CATEGORY}/${SUBPATH}/${KEYPATH}"
  fi

  echo "      <Route path=\"${ROUTE}\" element={<${COMPONENT_NAME} />} />" >> "$OUT"
done

# 8. End component
cat >> "$OUT" << 'EOF'
      <Route path="*" element={<div>Not Found</div>} />
    </Routes>
  );
}
EOF

echo "🎉 Clean GeneratedRoutes.jsx created."

