#!/bin/bash

OUT="src/layout/navigationIndex.js"
ROOT="src/pages"

echo "🚀 Generating NAV_INDEX from filesystem → $OUT"

cat > "$OUT" << 'EOF'
// AUTO-GENERATED BY tools/gen_nav_index.sh
// Do not edit manually.

const categoryMap = {
  app: "App",
  admin: "Admin",
  public: "Public",
};

const iconMap = {
  dashboard: "mdi-view-dashboard",
  trading: "mdi-chart-line",
  positions: "mdi-finance",
  portfolio: "mdi-briefcase",
  risk: "mdi-alert",
  liquidity: "mdi-water",
  execution: "mdi-crosshairs",
};

const shortcutMap = {
  dashboard: "⌘1",
  trading: "⌘2",
  portfolio: "⌘3",
  risk: "⌘4",
};

const humanize = (str) =>
  str
    .replace(/([A-Z])/g, " $1")
    .replace(/[-_]/g, " ")
    .replace(/\.[^/.]+$/, "")
    .trim()
    .replace(/\s+/g, " ")
    .replace(/^./, (c) => c.toUpperCase());

export const NAV_INDEX = [
EOF

# Scan all pages
find "$ROOT" -type f -name "*.jsx" | while read FILE; do
  REL=${FILE#src/pages/}          # e.g. admin/RiskCenter.jsx
  CATEGORY=$(echo "$REL" | cut -d'/' -f1)
  NAME=$(basename "$REL" .jsx)

  KEY=$(echo "$NAME" | tr 'A-Z' 'a-z')
  LABEL=$(echo "$NAME" | sed -E 's/([A-Z])/ \1/g' | sed 's/^ //')
  KEYPATH=$(echo "$NAME" | sed -E 's/([A-Z])/-\L\1/g' | sed 's/^-//')
  ROUTE="/$CATEGORY/$KEYPATH"

  cat >> "$OUT" << EOF
  {
    label: "${LABEL}",
    path: "${ROUTE}",
    category: categoryMap["$CATEGORY"] || "General",
    icon: iconMap["$KEY"] || "mdi-file",
    shortcut: shortcutMap["$KEY"] || null,
  },
EOF
done

cat >> "$OUT" << 'EOF'
].sort((a, b) => a.label.localeCompare(b.label));

export const openRoute = (path) => {
  // This assumes react-router navigation is wired elsewhere via EventBus or a router hook.
  window.dispatchEvent(new CustomEvent("nav:open", { detail: { path } }));
};
EOF

echo "🎉 NAV_INDEX generated."

