#!/bin/bash

OUT="src/layout/navMeta.js"
ROOT="src/pages"

echo "🚀 Generating iconMap + shortcutMap → $OUT"

cat > "$OUT" << 'EOF'
// AUTO-GENERATED BY tools/gen_icon_shortcuts.sh
// Do not edit manually.

export const iconMap = {
EOF

# Simple heuristics: map key words to icons
find "$ROOT" -type f -name "*.jsx" | while read FILE; do
  NAME=$(basename "$FILE" .jsx)
  KEY=$(echo "$NAME" | tr 'A-Z' 'a-z')

  ICON="mdi-file"
  case "$KEY" in
    *dashboard*) ICON="mdi-view-dashboard" ;;
    *trading*|*order*) ICON="mdi-chart-line" ;;
    *portfolio*) ICON="mdi-briefcase" ;;
    *risk*) ICON="mdi-alert" ;;
    *liquidity*) ICON="mdi-water" ;;
    *execution*) ICON="mdi-crosshairs" ;;
    *latency*) ICON="mdi-speedometer" ;;
    *replay*|*microstructure*) ICON="mdi-timeline" ;;
    *billing*|*funding*) ICON="mdi-cash-multiple" ;;
    *keys*|*auth*|*security*) ICON="mdi-shield-key" ;;
  esac

  echo "  \"$KEY\": \"$ICON\"," >> "$OUT"
done

cat >> "$OUT" << 'EOF'
};

export const shortcutMap = {
EOF

# Assign shortcuts to a few common keys
# (You can refine this later)
cat >> "$OUT" << 'EOF'
  "dashboard": "⌘1",
  "trading": "⌘2",
  "portfolio": "⌘3",
  "risk": "⌘4",
  "liquidity": "⌘5",
};
EOF

echo "🎉 navMeta.js generated."

