apiVersion: v1
kind: Secret
metadata:
  name: binance-rsa-credentials
  namespace: trading-platform
type: Opaque
stringData:
  BINANCE_API_KEY: "og9Ucf0v5PUlz7w5fSkoGv38nQ01bMZhIzr94huxCUrE8x0tWWPFThJiWs6W7Gv8"
  BINANCE_RSA_PRIVATE_KEY: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBvGxb2ah
    cltg47qrVrft/oAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIEDRxOW9o1g9Xt5v
    ujCf9fZXCrUE7ldLjg2svsSkBCCGAAAAoPj/OzwfmuGaAZ58h2ZHexWos30z5wptwpjAqw
    UTrNHUgUMw3/2TMrr2ExfQ1wuJoJxNRBE9B9LuM63D+D8uL2RA5mc2/5WpQ4zIDVDdra+H
    MDaK9rqcO1X7vKNgyOriRbnAKi98TSP/NffCXSLzy2uP8zIJa86z1Qkhz0BVu9MBIwucoz
    dLbJ4w4KDApXQ6EQJI4i5kUqNrloalqI7PsA8=
    -----END OPENSSH PRIVATE KEY-----
