"""add journal constraints and transaction hardening

Revision ID: 761e3b586b05
Revises: 79dc6d92e262
Create Date: 2026-02-13 11:33:16.075885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761e3b586b05'
down_revision: Union[str, Sequence[str], None] = '79dc6d92e262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
