apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-service
  namespace: trading-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kyc-service
  template:
    metadata:
      labels:
        app: kyc-service
    spec:
      nodeSelector:
        pool: core-services
      containers:
        - name: kyc-service
          image: europe-west2-docker.pkg.dev/globalquantx-prod/kyc/kyc-service:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: kyc-db-url
                  key: DATABASE_URL
            - name: NATS_URL
              value: nats://nats:4222
          ports:
            - containerPort: 8080

