apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: trading-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      nodeSelector:
        pool: backoffice
      containers:
        - name: api-gateway
          image: gcr.io/globalquantx-prod/api-gateway:v0.0.2
          imagePullPolicy: Always

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: apigw-db-url
                  key: DATABASE_URL
            - name: NATS_URL
              value: nats://nats:4222

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: cockroachdb-cloud-ca
              mountPath: /app/root.crt
              subPath: root.crt

      volumes:
        - name: cockroachdb-cloud-ca
          secret:
            secretName: cockroachdb-cloud-ca

