apiVersion: v1
kind: Secret
metadata:
  name: trading-service-secrets
  namespace: trading
type: Opaque
data:
  binance_api_key: SzJpMVdnR3RzNkJJREdiWEtMYTd3Z1JzbmlZWHZsdDlqN29Ub2xnRjlGcGlid2N5ZXc2ajNqdUR5eWVFQ3JKbg==
  binance_api_secret: TUROd3NuVE5XUW81bjdaYWJWNVo2U0k3YzFpUWI3T1hmcERibzlRWmlBWlJRNkxYUHZjd1hJZFd6dzdCTFhVMA==

