apiVersion: v1
kind: Service
metadata:
  name: trading-service
  namespace: trading
spec:
  selector:
    app: trading-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}

