apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: trading-platform
  labels:
    app: cockroachdb
spec:
  clusterIP: None
  ports:
    - port: 26257
      name: grpc
    - port: 26258
      name: sql
  selector:
    app: cockroachdb
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-public
  namespace: trading-platform
  labels:
    app: cockroachdb
spec:
  type: ClusterIP
  ports:
    - port: 26257
      name: grpc
    - port: 26258
      name: sql
  selector:
    app: cockroachdb

