apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: trading-platform
  labels:
    app: wallet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: europe-west2-docker.pkg.dev/globalquantx-prod/api/wallet-service:v0.0.1
          imagePullPolicy: Always

          env:
            - name: DATABASE_URL
              value: "postgresql://root@cockroachdb:26257/globalquantx?sslmode=disable"

            - name: NATS_URL
              value: "nats://nats:4222"

            - name: RUST_LOG
              value: info

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

