apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: trading-platform
  labels:
    app: wallet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: wallet-service:v0.0.1
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: platform-config

          env:
            - name: NATS_URL
              value: "nats://nats.trading-platform.svc.cluster.local:4222"
            - name: RUST_LOG
              value: "info"

          ports:
            - containerPort: 8080

