# k8s/base/wallet-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: trading-platform
spec:
  selector:
    app: wallet-service
  ports:
    - port: 8080
      targetPort: 8080

