apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-service
  namespace: trading-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onboarding-service
  template:
    metadata:
      labels:
        app: onboarding-service
    spec:
      nodeSelector:
        pool: core-services
      containers:
        - name: onboarding-service
          image: europe-west2-docker.pkg.dev/globalquantx-prod/onboarding/onboarding-service:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: onboarding-db-url
                  key: DATABASE_URL
            - name: NATS_URL
              value: nats://nats:4222
          ports:
            - containerPort: 8080

