# k8s/base/onboarding-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: onboarding-service
  namespace: trading-platform
spec:
  selector:
    app: onboarding-service
  ports:
    - port: 8080
      targetPort: 8080

