creation_rules:
  - path_regex: secrets/.*\.yaml$
    age: ["age1ctzaswt7vfvtjkfmlyah2areclan9gvc8v30twf05vccfq2k0f5qq9qg0y"]
  - path_regex: .*\.enc\.yaml$
    age: ["age1ctzaswt7vfvtjkfmlyah2areclan9gvc8v30twf05vccfq2k0f5qq9qg0y"]

