apiVersion: v1
kind: Secret
metadata:
  name: aml-db-url
  namespace: trading-platform
type: Opaque
stringData:
  DATABASE_URL: "postgresql://mo:FUa7p0w1phYKChdQBCwehg@social-sardine-13508.jxf.gcp-europe-west2.cockroachlabs.cloud:26257/globalquantx?sslmode=verify-full&sslrootcert=/cockroach-certs/root.crt"

