apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config-compliance
  namespace: compliance-platform
data:
  DB_USER: "compliance_user"
  DB_PASSWORD: ""
  DB_HOST: "cockroachdb-compliance.compliance-platform.svc.cluster.local"
  DB_PORT: "26257"
  DB_SSLMODE: "disable"
  DB_NAME: "compliance_platform"
