apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-service
  namespace: trade-platform
  labels:
    app: risk-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: risk-service
  template:
    metadata:
      labels:
        app: risk-service
    spec:
      containers:
        - name: risk-service
          image: risk-service:v.0.0.1
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: platform-config-trade

          env:
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: RUST_LOG
              value: "info"

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: risk-service
  namespace: trade-platform
spec:
  type: ClusterIP
  selector:
    app: risk-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080

