apiVersion: ENC[AES256_GCM,data:RoE=,iv:l1idMpGMB6uwhsQo+Z2TmELa63KWIG0I8KBVgYqdu70=,tag:di1Nu/+dsdu/05s9Zz+Jrg==,type:str]
kind: ENC[AES256_GCM,data:3ey5v5ry,iv:bsNjih9GY1POehII9AXidtRmVZ5Mjwwcb50doNANcik=,tag:W3QXJ28VnIoqapZXmEuY6w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SK8ynfN/W7AoNw==,iv:Wrchb3gy1Dvja+HE8596ptbNUZgtFA+j88Cd8cMj4Gk=,tag:0PTHbwRZxL155XM26/nBuA==,type:str]
    namespace: ENC[AES256_GCM,data:nvBWp1T4CY90o1sgbFe50w==,iv:UHt8dwQ+OQTSM4VXbNEB9R6+reUYpEeJN4xONqO48W8=,tag:fkL4Pxr8gUyG7nwrEfjQgg==,type:str]
type: ENC[AES256_GCM,data:2mxtYNgY,iv:Ji/N8gupOM/rAb6SaDAbQnwxoE3FBaRppDbI0Rvl2Kc=,tag:eumaSN4CWtK+FBzDmI0I/g==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:uIoXBSNVIAWChyTtL0LeUDQad9VVz0+0b9jMQTS96PE7xCOctkCz7k69IQQXYsDQLAN5gOzOQYH6MIlIW7r8L3QpsxtcldQ5hY779qKyxFbwrewoUt385EFjpnnQVWZxEbjPv3PsBWUjU/mQoWwYnisxO4qYqgS59+t/6BQ9VY16gXeVcdEmPYsW0wM6GS0oYJfc6Qp7cZTH05bXIKzdJDO+V/hN7G9hyXTHv+wmNxZA,iv:W7/ej7BLNF11CKhnrG7xOcbiKoNES3TPuPHu3ZFE7Ok=,tag:RqfC/k5YwGTPp9/Cqu4d3Q==,type:str]
sops:
    age:
        - recipient: age1ctzaswt7vfvtjkfmlyah2areclan9gvc8v30twf05vccfq2k0f5qq9qg0y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTVBQUWtxV0V1NUptcm1u
            eWVPOUZVMHIzWlpyVnZKZlZUY1BGZk9SZURzCjhFRnZzMWNpc1JiKy9BR3NJKzRv
            Q3Z0cTN4RGFEcWkvaGlsZTZvRDREd3cKLS0tIGV3UU9TQ2s4VDdzZWxtSGRubll3
            VHJTY0ZSVDZTTG5kcTQxVElocXdDQ1UK1pDdsUz3Z2nXyWPyq07sO2ftizc7HWgV
            opWmQR1Nht99aeYzxAMk9gcRMMC+C72UgQ+A5ulK1DBjgqQ9O4LoWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T13:12:09Z"
    mac: ENC[AES256_GCM,data:rpYGQ67i9PwCNl9UVOise+ihkFNIohSdv58S+fAyZCqwWY+mXq0fAQrLJg0gIlcfiZZPfQcSBUnyhKYW84YmjiFo2Q1nl5xNB+qI7S9bmmS4zfOWZzAYqSHz+fg/pU0d9+FYUMxG+QIPJrcvbOyhQjUZN5D24CHNVTR3WpkBTXw=,iv:uOTmOOGUwiq+kHtBHhX8NYxICQ7qUSsZNvJ0x11zBxE=,tag:oyBhT07YhBdcvevFP82efQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
