apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service
  namespace: trading-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: market-data-service
  template:
    metadata:
      labels:
        app: market-data-service
    spec:
      nodeSelector:
        pool: trading-compute
      containers:
        - name: market-data-service
          image: europe-west2-docker.pkg.dev/globalquantx-prod/market-data/market-data-service:v0.0.1
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: market-data-db-url
                  key: DATABASE_URL
            - name: NATS_URL
              value: nats://nats:4222
          ports:
            - containerPort: 8080

          volumeMounts:
            - name: cockroachdb-ca
              mountPath: /app/root.crt
              subPath: root.crt
      volumes:
        - name: cockroachdb-ca
          secret:
            secretName: apigw-db-url
            items:
              - key: ca.crt
                path: root.crt
