apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: trading-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: gcr.io/globalquantx-prod/auth-service:v0.0.9
        imagePullPolicy: IfNotPresent

        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: auth-db-url
              key: DATABASE_URL

        - name: NATS_URL
          value: "nats://nats:4222"

        - name: REFRESH_TOKEN_KEY
          valueFrom:
            secretKeyRef:
              name: auth-refresh-key
              key: REFRESH_TOKEN_KEY

        ports:
        - containerPort: 9001

        livenessProbe:
          httpGet:
            path: /live
            port: 9001
          initialDelaySeconds: 5
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /ready
            port: 9001
          initialDelaySeconds: 5
          periodSeconds: 10

        volumeMounts:
        - name: cockroachdb-ca
          mountPath: /app/root.crt
          subPath: root.crt

      volumes:
      - name: cockroachdb-ca
        secret:
          secretName: auth-db-url
          items:
          - key: ca.crt
            path: root.crt

