apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: trading-platform
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:v.0.0.1
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          # Load all shared platform variables
          envFrom:
            - configMapRef:
                name: platform-config-identity

          # Explicitly inject DATABASE_URL so SQLx can connect
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config-identity
                  key: DATABASE_URL

            - name: NATS_URL
              value: "nats://nats:4222"

            - name: RUST_LOG
              value: "info"

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: trading-platform
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080

